import random
import math

word = input("Enter a memorable word of atleast 8 characters: ")

p1 = "blank"
n1 = "blank"
tsls = "blank"
#tslw stands for "the super long string"

text = word
letter1 = text[3] 
letter2 = text[4] 
letter3 = text[5] 

letter = letter1 + letter2 + letter3

n1 = random.randrange(1,9)


# 1579 characters 
#  do roughly randrange(21579)
if n1 == 1:
    tsls = (
        "Accordingtoallknownlawsofaviationthereisnowayabeeshouldbeabletofly "
        "Itswingsaretoosmalltogetitsfatlittlebodyofftheground "
        "Thebeeofcoursefliesanywaybecausebeesdontcarewhathumansthinkisimpossible "
        "YellowblackYellowblackYellowblackYellowblack Oohblackandyellow Letsshakeitupalittle "
        "BarryBreakfastisready Coming Hangonasecond Hello Barry Adam Canyoubelievethisishappening Icant Illpickyouup "
        "Lookingsharp UsethestairsYourfatherpaidgoodmoneyforthose SorryImexcited Heresthegraduate "
        "Wereveryproudofyouson AperfectreportcardallBs Veryproud MaIgotathinggoinghere Yougotlintonyourfuzz OwThatsme "
        "WavetousWellbeinrow118000 Bye BarryItoldyoustopflyinginthehouse HeyAdam HeyBarry Isthatfuzzgel "
        "AlittleSpecialdaygraduation NeverthoughtIdmakeit Threedaysgradeschoolthreedayshighschool "
        "Thosewereawkward ThreedayscollegeImgladItookadayandhitchhikedaroundTheHive Youdidcomebackdifferent "
        "HiBarryArtiegrowingamustacheLooksgood HearaboutFrankie Yeah Yougoingtothefuneral NoImnotgoing "
        "Everybodyknowsstingsomeoneyoudie Dontwasteitonasquirrel Suchahothead Iguesshecouldhavejustgottenoutoftheway "
        "Ilovethisincorporatinganamusementparkintoourday Thatswhywedontneedvacations "
        "Boyquiteabitofpompunderthecircumstances WellAdamtodaywearemen Weare Bee-men Amen Hallelujah "
        "Studentsfacultydistinguishedbees pleasewelcomeDeanBuzzwell WelcomeNewHiveCitygraduatingclassof915 "
        "ThatconcludesourceremoniesAndbeginsyourcareeratHonexIndustries Willwepickourjobtoday "
        "Ihearditsjustorientation HeadsupHerewego"
    )

    
# 1796 characters
if (n1 == 2) :{

print("""Keepyourhandsandantennasinsidethetramatalltimes Wonderwhatitllbelike Alittlescary WelcometoHonexadivisionofHonescoandapartoftheHexagonGroup Thisisit Wow Wow Weknowthatyouasabeehaveworkedyourwholelifetogettothepointwhereyoucanworkforyourwholelife HoneybeginswhenourvaliantPollenJocksbringthenectartoTheHive Ourtop-secretformulaisautomaticallycolor-correctedscent-adjustedandbubble-contouredintothissoothingsweetsyrupwithitsdistinctivegoldenglowyouknowasHoney Thatgirlwashot Shesmycousin Sheis Yeswereallcousins RightYoureright AtHonexweconstantlystrivetoimproveeveryaspectofbeeexistence Thesebeesarestress-testinganewhelmettechnology Whatdoyouthinkhemakes Notenough HerewehaveourlatestadvancementtheKrelman Whatdoesthatdo Catchesthatlittlestrandofhoneythathangsafteryoupourit Savesusmillions CananyoneworkontheKrelman OfcourseMostbeejobsaresmallones Butbeesknowthateverysmalljobifitsdonewellmeansalot Butchoosecarefullybecauseyoullstayinthejobyoupickfortherestofyourlife ThesamejobtherestofyourlifeIdidntknowthat Whatsthedifference Youllbehappytoknowthatbeesasaspecieshaventhadonedayoffin27millionyears Soyoulljustworkustodeath Wellsuretry WowThatblewmymind "Whatsthedifference" Howcanyousaythat Onejobforever Thatsaninsanechoicetohavetomake ImrelievedNowweonlyhavetomakeonedecisioninlife ButAdamhowcouldtheyneverhavetoldusthat WhywouldyouquestionanythingWerebees WerethemostperfectlyfunctioningsocietyonEarth Youeverthinkmaybethingsworkalittletoowellhere LikewhatGivemeoneexample IdontknowButyouknowwhatImtalkingabout PleaseclearthegateRoyalNectarForceonapproach WaitasecondCheckitout HeythosearePollenJocks Wow Iveneverseenthemthisclose TheyknowwhatitslikeoutsideTheHive Yeahbutsomedontcomeback """   )

}
    

# 1684 characters  
if (n1 == 3) :{

print("HeyJocks HiJocks Youguysdidgreat Youremonsters YoureskyfreaksIloveitIloveit Iwonderwheretheywere Idontknow Theirdaysnotplanned OutsideTheHiveflyingwhoknowswheredoingwhoknowswhat YoucantjustdecidetobeaPollenJockYouhavetobebredforthat Right LookThatsmorepollenthanyouandIwillseeinalifetime Itsjustastatussymbol Beesmaketoomuchofit PerhapsUnlessyourewearingitandtheladiesseeyouwearingit Thoseladies Arenttheyourcousinstoo DistantDistant Lookatthesetwo CoupleofHiveHarrys Letshavefunwiththem ItmustbedangerousbeingaPollenJock YeahOnceabearpinnedmeagainstamushroom Hehadapawonmythroatandwiththeotherhewasslappingme Ohmy IneverthoughtIdknockhimout Whatwereyoudoingduringthis Tryingtoalerttheauthorities Icanautographthat Alittlegustyouttheretodaywasntitcomrades YeahGusty Werehittingasunflowerpatchsixmilesfromheretomorrow Sixmileshuh Barry Apuddlejumpforusbutmaybeyourenotupforit MaybeIam Youarenot Weregoing0900atJ-Gate Whatdoyouthinkbuzzy-boy Areyoubeeenough ImightbeItalldependsonwhat0900means HeyHonex Dadyousurprisedme Youdecidewhatyoureinterestedin Welltheresalotofchoices Butyouonlygetone Doyouevergetboreddoingthesamejobeveryday Sonletmetellyouaboutstirring Yougrabthatstickandyoujustmoveitaroundandyoustiritaround Yougetyourselfintoarhythm Itsabeautifulthing YouknowDadthemoreIthinkaboutit maybethehoneyfieldjustisntrightforme Youwerethinkingofwhatmakingballoonanimals Thatsabadjobforaguywithastinger Janetyoursonsnotsurehewantstogointohoney Barryyouaresofunnysometimes Imnottryingtobefunny YourenotfunnyYouregoingintohoneyOursonthestirrer Youregonnabeastirrer")

}
    
# 1630 characters  
# do like randRang(41630)  
if (n1 == 4) :{

print("""Nooneslisteningtome WaittillyouseethesticksIhave Icouldsayanythingrightnow Imgonnagetananttattoo Letsopensomehoneyandcelebrate MaybeIllpiercemythoraxShavemyantennaeShackupwithagrasshopperGetagoldtoothandcalleverybody"dawg" Imsoproud Werestartingworktoday Todaystheday ComeonAllthegoodjobswillbegone Yeahright Pollencountingstuntbeepouringstirrerfrontdeskhairremoval Isitstillavailable HangonTwoleft OneofthemsyoursCongratulations Steptotheside Whatdyouget PickingcrudoutStellar Wow Coupleofnewbies YessirOurfirstdayWeareready Makeyourchoice Youwanttogofirst Noyougo OhmyWhatsavailable Restroomattendantsopennotforthereasonyouthink AnychanceofgettingtheKrelman Sureyoureon ImsorrytheKrelmanjustclosedout Waxmonkeysalwaysopen TheKrelmanopenedupagain Whathappened AbeediedMakesanopeningSeeHesdeadAnotherdeadone DeadyDeadifiedTwomoredead DeadfromtheneckupDeadfromtheneckdownThatslife Ohthisissohard Heatingcoolingstuntbeepourerstirrerhumminginspectornumbersevenlintcoordinatorstripesupervisormitewrangler BarrywhatdoyouthinkIshouldBarry Barry Allrightwevegotthesunflowerpatchinquadrantnine Whathappenedtoyou Whereareyou Imgoingout OutOutwhere Outthere Ohno IhavetobeforeIgotoworkfortherestofmylife YouregonnadieYourecrazyHello Anothercallcomingin IfanyonesfeelingbravetheresaKoreandelion83rdthatgetstheirrosestoday Heyguys Lookatthat Isntthatthekidwesawyesterday Holditsonflightdecksrestricted ItsOKLouWeregonnatakehimup ReallyFeelingluckyareyou SignherehereJustinitialthat Thankyou OK""")

}
    

# 1589 characters    
if (n1 == 5) :{

print("Yougotarainadvisorytodayandasyouallknowbeescannotflyinrain SobecarefulAsalwayswatchyourbroomshockeysticksdogsbirdsbearsandbats AlsoIgotacoupleofreportsofrootbeerbeingpouredonus Murphysinahomebecauseofitbabblinglikeacicada Thatsawful Andareminderforyourookiesbeelawnumberoneabsolutelynotalkingtohumans Allrightlaunchpositions BuzzbuzzbuzzbuzzBuzzbuzzbuzzbuzzBuzzbuzzbuzzbuzz Blackandyellow Hello Youreadyforthishotshot YeahYeahbringiton Windcheck Antennaecheck Nectarpackcheck Wingscheck Stingercheck Scaredoutofmyshortscheck OKladies letsmoveitout Poundthosepetuniasyoustripedstem-suckers Allofyoudrainthoseflowers WowImout IcantbelieveImout Soblue Ifeelsofastandfree Boxkite Wow Flowers ThisisBlueLeaderWehaverosesvisual Bringitaround30degreesandhold Roses 30degreesrogerBringingitaround Standtothesidekid Itsgotabitofakick Thatisonenectarcollector Everseepollinationupclose Nosir IpickupsomepollenheresprinkleitoverhereMaybeadashoverthereapinchonthatone SeethatItsalittlebitofmagic ThatsamazingWhydowedothat ThatspollenpowerMorepollenmoreflowersmorenectarmorehoneyforus Cool ImpickingupalotofbrightyellowCouldbedaisiesDontweneedthose Copythatvisual WaitOneoftheseflowersseemstobeonthemove SayagainYourereportingamovingflower Affirmative Thatwasontheline ThisisthecoolestWhatisit IdontknowbutImlovingthiscolor Itsmellsgood NotlikeaflowerbutIlikeit Yeahfuzzy Chemical-y CarefulguysItsalittlegrabby Mysweetlordofbees Candy-braingetoffthere Problem Guys")

}


# 1702 characters    
if (n1 == 6) :{

print("Thiscouldbebad Affirmative Veryclose Gonnahurt Mamaslittleboy Youarewayoutofpositionrookie Cominginatyoulikeamissile Helpme Idontthinktheseareflowers Shouldwetellhim Ithinkheknows Whatisthis Matchpoint Youcanstartpackinguphoneybecauseyoureabouttoeatit Yowser Gross Theresabeeinthecar Dosomething Imdriving Hibee Hesbackhere Hesgoingtostingme NobodymoveIfyoudontmovehewontstingyouFreeze Heblinked SprayhimGranny Whatareyoudoing Wowthetensionlevelouthereisunbelievable Igottagethome CantflyinrainCantflyinrainCantflyinrain MaydayMaydayBeegoingdown Kencouldyouclosethewindowplease Kencouldyouclosethewindowplease CheckoutmynewresumeImadeitintoafold-outbrochureYouseeFoldsout OhnoMorehumansIdontneedthis Whatwasthat MaybethistimeThistimeThistimeThistimeThistimeThisDrapes Thatisdiabolical ItsfantasticItsgotallmyspecialskillsevenmytop-tenfavoritemovies WhatsnumberoneStarWars NahIdontgoforthatkindofstuff NowonderweshouldnttalktothemTheyreoutoftheirminds WhenIleaveajobinterviewtheyreflabbergastedcantbelievewhatIsay TheresthesunMaybethatsawayout Idontrememberthesunhavingabig75onit IpredictedglobalwarmingIcouldfeelitgettinghotterAtfirstIthoughtitwasjustme WaitStopBee StandbackThesearewinterboots Wait Dontkillhim YouknowImallergictothemThisthingcouldkillme Whydoeshislifehavelessvaluethanyours WhydoeshislifehaveanylessvaluethanmineIsthatyourstatement ImjustsayingalllifehasvalueYoudontknowwhathescapableoffeeling Mybrochure Thereyougolittleguy ImnotscaredofhimItsanallergicthing Putthatonyourresumebrochure Mywholefacecouldpuffup Makeitoneofyourspecialskills")

}
    

# 1576 characters    
if (n1 == 7) :{

print("""Knockingsomeoneoutisalsoaspecialskill RightByeVanessaThanks VanessanextweekYogurtnight SureKenYouknowwhatever Youcouldputcarobchipsonthere Bye Supposedtobelesscalories Bye IgottasaysomethingShesavedmylifeIgottasaysomething Allrighthereitgoes Nah WhatwouldIsay IcouldreallygetintroubleItsabeelawYourenotsupposedtotalktoahuman IcantbelieveImdoingthisIvegotto OhIcantdoitComeon NoYesNoDoitIcant HowshouldIstartit"Youlikejazz"Nothatsnogood HereshecomesSpeakyoufool Hi ImsorryYouretalking YesIknow Youretalking Imsosorry NoitsOKItsfine IknowImdreamingButIdontrecallgoingtobed WellImsurethisisverydisconcerting ThisisabitofasurprisetomeImeanyoureabee IamAndImnotsupposedtobedoingthisbuttheywerealltryingtokillme AndifitwasntforyouIhadtothankyouItsjusthowIwasraised ThatwasalittleweirdImtalkingwithabee Yeah ImtalkingtoabeeAndthebeeistalkingtome IjustwanttosayImgrateful Illleavenow WaitHowdidyoulearntodothat What Thetalkingthing SamewayyoudidIguess"MamaDadahoney"Youpickitup Thatsveryfunny Yeah BeesarefunnyIfwedidntlaughwedcrywithwhatwehavetodealwith AnywayCanIgetyousomething Likewhat IdontknowImeanIdontknowCoffee Idontwanttoputyouout ItsnotroubleIttakestwominutes Itsjustcoffee Ihatetoimpose Dontberidiculous ActuallyIwouldloveacup Heyyouwantrumcake Ishouldnt Havesome NoIcant Comeon Imtryingtoloseacouplemicrograms Where Thesestripesdonthelp Youlookgreat Idontknowifyouknowanythingaboutfashion Areyouallright No""")

}
    

# 1555 characters    
if (n1 == 8) :{

print("""HesmakingthetieinthecabastheyreflyingupMadison Hefinallygetsthere Herunsupthestepsintothechurch Theweddingison Andhesays"Watermelon IthoughtyousaidGuatemalan WhywouldImarryawatermelon" Isthatabeejoke Thatsthekindofstuffwedo Yeahdifferent SowhatareyougonnadoBarry AboutworkIdontknow IwanttodomypartforTheHivebutIcantdoitthewaytheywant Iknowhowyoufeel Youdo Sure MyparentswantedmetobealawyeroradoctorbutIwantedtobeaflorist Really Myonlyinterestisflowers Ournewqueenwasjustelectedwiththatsamecampaignslogan AnywayifyoulookTheresmyhiverightthereSeeit YoureinSheepMeadow YesImrightofftheTurtlePond NowayIknowthatareaIlostatoeringthereonce Whydogirlsputringsontheirtoes Whynot Itslikeputtingahatonyourknee MaybeIlltrythat Youallrightmaam OhyeahFine Justhavingtwocupsofcoffee Anywaythishasbeengreat Thanksforthecoffee Yeahitsnotrouble SorryIcouldntfinishitIfIdidIdbeuptherestofmylife Areyou CanItakeapieceofthiswithme SureHerehaveacrumb Thanks Yeah AllrightWellthenIguessIllseeyouaroundOrnot OKBarry Andthankyousomuchagainforbefore OhthatThatwasnothing WellnotnothingbutAnyway Thiscantpossiblywork Hesallsettogo Wemayaswelltryit OKDavepullthechute Soundsamazing Itwasamazing Itwasthescariesthappiestmomentofmylife HumansIcantbelieveyouwerewithhumans Giantscaryhumans Whatweretheylike HugeandcrazyTheytalkcrazy Theyeatcrazygiantthings Theydrivecrazy DotheytryandkillyoulikeonTV SomeofthemButsomeofthemdont Howdyougetback Poodle""")

}


# 1614 characters 
if (n1 == 9) :{

print("""YoudiditandImgladYousawwhateveryouwantedtosee Youhadyour"experience"Nowyoucanpickoutyourjobandbenormal Well Well WellImetsomeone YoudidWassheBee-ish AwaspYourparentswillkillyou Nonononotawasp Spider Imnotattractedtospiders IknowitsthehottestthingwiththeeightlegsandallIcantgetbythatface Sowhoisshe Sheshuman NonoThatsabeelawYouwouldntbreakabeelaw HernamesVanessa Ohboy ShessoniceAndshesaflorist OhnoYouredatingahumanflorist Werenotdating YoureflyingoutsideTheHivetalkingtohumansthatattackourhomeswithpowerwashersandM-80sOne-eighthastickofdynamite ShesavedmylifeAndsheunderstandsme Thisisover Eatthis ThisisnotoverWhatwasthat Theycallitacrumb Itwassostinginstripey Andthatsnotwhattheyeat Thatswhatfallsoffwhattheyeat YouknowwhataCinnabonis No ItsbreadandcinnamonandfrostingTheyheatitup Sitdown reallyhot Listentome WearenotthemWereus Theresusandtheresthem Yesbutwhocandenytheheartthatisyearning TheresnoyearningStopyearningListentome YouhavegottostartthinkingbeemyfriendThinkingbee Thinkingbee Thinkingbee ThinkingbeeThinkingbeeThinkingbeeThinkingbee ThereheisHesinthepool YouknowwhatyourproblemisBarry Igottastartthinkingbee Howmuchlongerwillthisgoon ItsbeenthreedaysWhyarentyouworking Ivegotalotofbiglifedecisionstothinkabout WhatlifeYouhavenolife YouhavenojobYourebarelyabee Woulditkillyoutomakealittlehoney BarrycomeoutYourfatherstalkingtoyou Martinwouldyoutalktohim BarryImtalkingtoyou Youcoming Goteverything Allset GoaheadIllcatchup Dontbetoolong Watchthis Vanessa""")

}
    
print(" ")
print(tsls)



